using System;
using System.Collections.Generic;

namespace AppService.Core.EntitiesEstadisticas
{
    public partial class Mcvtam
    {
        public int RecordNumber { get; set; }
        public string Transaccion { get; set; }
        public decimal? Documento { get; set; }
        public string Tracanc { get; set; }
        public decimal? Docucanc { get; set; }
        public decimal? Orden { get; set; }
        public decimal? Cliente { get; set; }
        public string Vendedor { get; set; }
        public string Producto { get; set; }
        public DateTime? FechaFactura { get; set; }
        public decimal? MesContable { get; set; }
        public decimal? AloContable { get; set; }
        public decimal? Cantidad { get; set; }
        public decimal? PrecioVenta { get; set; }
        public decimal? PrecioLista { get; set; }
        public decimal? ValorVenta { get; set; }
        public decimal? ValorLista { get; set; }
        public string RegionVta { get; set; }
        public string Grupo { get; set; }
        public string Zona { get; set; }
        public decimal? Oficina { get; set; }
        public decimal? Partes { get; set; }
        public string MetodoPrecio { get; set; }
        public string TipoPapel { get; set; }
        public string TipoProdu { get; set; }
        public string Anulada { get; set; }
        public decimal? Impuesto { get; set; }
        public string NombreCliente { get; set; }
        public string Linea1 { get; set; }
        public string Familia { get; set; }
        public decimal? Tipo { get; set; }
        public decimal? MedidaBase { get; set; }
        public decimal? MedidaVariable { get; set; }
        public decimal? MedEnt { get; set; }
        public decimal? MedNum { get; set; }
        public decimal? MedDec { get; set; }
        public decimal? TotalKgPapel { get; set; }
        public decimal? TotalKgCarbon { get; set; }
        public decimal? TotalBsPapel { get; set; }
        public decimal? TotalBsCarbon { get; set; }
        public decimal? Totalvariable { get; set; }
        public decimal? Totalmatotros { get; set; }
        public decimal? Bsmc { get; set; }
        public decimal? PorcMc { get; set; }
        public decimal? Bsmclista { get; set; }
        public decimal? ProcMclista { get; set; }
        public decimal? TotalKgSpot { get; set; }
        public decimal? TotalBsSpot { get; set; }
        public decimal? CostoTt { get; set; }
        public decimal? PiesTt { get; set; }
        public decimal? BsTt { get; set; }
        public decimal? Tabla { get; set; }
        public decimal? PorcComision { get; set; }
        public decimal? Comision { get; set; }
        public decimal? PorcOverride { get; set; }
        public decimal? Override { get; set; }
        public decimal? PorcOverger { get; set; }
        public decimal? Overger { get; set; }
        public decimal? Concesion { get; set; }
        public decimal? Millares { get; set; }
        public string NombreRegion { get; set; }
        public string NombreOficina { get; set; }
        public string NombreSup { get; set; }
        public string NombreVend { get; set; }
        public string Supervisor { get; set; }
        public decimal? Signo { get; set; }
        public string NombreLinea { get; set; }
        public decimal? Conteo { get; set; }
        public decimal? BsPlaca { get; set; }
        public decimal? Correlativo { get; set; }
        public decimal? Renglon { get; set; }
        public DateTime? FechaOrden { get; set; }
        public decimal? PiesTotal { get; set; }
        public decimal? Materialesespeciales { get; set; }
        public decimal? PorcMcPapel { get; set; }
        public decimal? PorcMcFinan { get; set; }
        public decimal? BsMcPapel { get; set; }
        public decimal? BsMcFinan { get; set; }
        public decimal? PorcMcPapelsc { get; set; }
        public decimal? PorcMcFinansc { get; set; }
        public decimal? BsMcPapelsc { get; set; }
        public decimal? BsMcFinansc { get; set; }
        public decimal? SdfV { get; set; }
        public decimal? SdfTl { get; set; }
        public decimal? SdfGo { get; set; }
        public decimal? SdfGr { get; set; }
        public decimal? SdfGic { get; set; }
        public decimal? SdfCic { get; set; }
        public decimal? SdfGop { get; set; }
        public string CodGo { get; set; }
        public string CodGr { get; set; }
        public string CodGic { get; set; }
        public string CodCic { get; set; }
        public string CodGop { get; set; }
        public decimal? ComisionGo { get; set; }
        public decimal? ComisionGic { get; set; }
        public decimal? ComisionCic { get; set; }
        public decimal? ComisionGop { get; set; }
        public decimal? PorcGo { get; set; }
        public decimal? PorcGic { get; set; }
        public decimal? PorcCic { get; set; }
        public decimal? PorcGop { get; set; }
        public string Nocalculamc { get; set; }
        public decimal? RprecioVenta { get; set; }
        public decimal? RprecioLista { get; set; }
        public decimal? RvalorVenta { get; set; }
        public decimal? RvalorLista { get; set; }
        public decimal? RtotalBsPapel { get; set; }
        public decimal? RtotalBsCarbon { get; set; }
        public decimal? Rtotalvariable { get; set; }
        public decimal? Rtotalmatotros { get; set; }
        public decimal? Rbsmc { get; set; }
        public decimal? Rbsmclista { get; set; }
        public decimal? RtotalBsSpot { get; set; }
        public decimal? RcostoTt { get; set; }
        public decimal? RbsTt { get; set; }
        public decimal? Rcomision { get; set; }
        public decimal? Roverride { get; set; }
        public decimal? Roverger { get; set; }
        public decimal? RbsMcPapel { get; set; }
        public decimal? RbsMcFinan { get; set; }
        public decimal? RbsMcPapelsc { get; set; }
        public decimal? RbsMcFinansc { get; set; }
        public decimal? RsdfV { get; set; }
        public decimal? RsdfTl { get; set; }
        public decimal? RsdfGo { get; set; }
        public decimal? RsdfGr { get; set; }
        public decimal? RsdfGic { get; set; }
        public decimal? RsdfCic { get; set; }
        public decimal? RsdfGop { get; set; }
        public decimal? RcomisionGo { get; set; }
        public decimal? RcomisionGic { get; set; }
        public decimal? RcomisionCic { get; set; }
        public decimal? RcomisionGop { get; set; }
        public decimal? PorcMcFinanEmb { get; set; }
        public decimal? BsMcFinanEmb { get; set; }
        public decimal? PorcMcFinanscEmb { get; set; }
        public decimal? BsMcFinanscEmb { get; set; }
        public decimal PiesTotales { get; set; }
        public decimal PiesLineales { get; set; }
        public decimal PiesVenta { get; set; }
        public decimal KilosOrden { get; set; }
        public decimal PiesCuadrado { get; set; }
    }
}
