CREATE TABLE AppCalculadora (
                                Id INT PRIMARY KEY IDENTITY(1,1),
                                IdVendedor NVARCHAR(4) NOT NULL,
                                IdMunicipio INT NOT NULL,
                                DescripcionMunicipio NVARCHAR(255) NOT NULL,
                                IdCondPago INT NOT NULL,
                                DescripcionCondPago NVARCHAR(255) NOT NULL,
                                IdMtrTipoMonedaPago INT NOT NULL,
                                DescripcionTipoMonedaPAgo NVARCHAR(255) NOT NULL,
                                IdSubcategoria INT NOT NULL,
                                DescripcionSubcategoria NVARCHAR(255) NOT NULL,
                                IdProducto INT NOT NULL,
                                DescripcionProducto NVARCHAR(255) NOT NULL,
                                Cantidad DECIMAL(18, 2) NOT NULL,
                                IdUnidad INT NOT NULL,
                                DescripcionUnidad NVARCHAR(255) NOT NULL,
                                Cantidad_X_Unidad DECIMAL(18) NOT NULL,
                                CantidadConvertida DECIMAL(18, 4) NOT NULL,
                                MedidaBasica NVARCHAR(50) NOT NULL,
                                MedidaOpuesta NVARCHAR(50) NOT NULL,
                                PrecioMinimo DECIMAL(18, 4) NOT NULL,
                                PrecioMaximo DECIMAL(18, 4) NOT NULL,
                                Precio DECIMAL(18, 4) NOT NULL,
                                Total DECIMAL(18, 2) NOT NULL,
                                CalculoId INT NULL,
                                UserCreate NVARCHAR(50) NOT NULL,
                                UserUpdate NVARCHAR(50) NULL,
                                CreatedAt DATETIME NOT NULL,
                                UpdatedAt DATETIME NULL,
                                SearchText NVARCHAR(MAX) NULL
);