CREATE PROCEDURE UpdateAppCalculadora
    @Id INT,
    @IdVendedor NVARCHAR(50),
    @IdMunicipio INT,
    @DescripcionMunicipio NVARCHAR(255),
    @IdCondPago INT,
    @DescripcionCondPago NVARCHAR(255),
    @IdMtrTipoMonedaPago INT,
    @DescripcionTipoMonedaPAgo NVARCHAR(255),
    @IdSubcategoria INT,
    @DescripcionSubcategoria NVARCHAR(255),
    @IdProducto INT,
    @DescripcionProducto NVARCHAR(255),
    @Cantidad DECIMAL(18, 2),
    @IdUnidad INT,
    @DescripcionUnidad NVARCHAR(255),
    @Cantidad_X_Unidad DECIMAL(18, 2),
    @CantidadConvertida DECIMAL(18, 2),
    @MedidaBasica NVARCHAR(50),
    @MedidaOpuesta NVARCHAR(50),
    @PrecioMinimo DECIMAL(18, 2),
    @PrecioMaximo DECIMAL(18, 2),
    @Precio DECIMAL(18, 2),
    @Total DECIMAL(18, 2),
    @CalculoId INT = NULL,
    @UserUpdate NVARCHAR(50),
    @SearchText NVARCHAR(MAX) = NULL
AS
BEGIN
UPDATE AppCalculadora
SET
    IdVendedor = @IdVendedor,
    IdMunicipio = @IdMunicipio,
    DescripcionMunicipio = @DescripcionMunicipio,
    IdCondPago = @IdCondPago,
    DescripcionCondPago = @DescripcionCondPago,
    IdMtrTipoMonedaPago = @IdMtrTipoMonedaPago,
    DescripcionTipoMonedaPAgo = @DescripcionTipoMonedaPAgo,
    IdSubcategoria = @IdSubcategoria,
    DescripcionSubcategoria = @DescripcionSubcategoria,
    IdProducto = @IdProducto,
    DescripcionProducto = @DescripcionProducto,
    Cantidad = @Cantidad,
    IdUnidad = @IdUnidad,
    DescripcionUnidad = @DescripcionUnidad,
    Cantidad_X_Unidad = @Cantidad_X_Unidad,
    CantidadConvertida = @CantidadConvertida,
    MedidaBasica = @MedidaBasica,
    MedidaOpuesta = @MedidaOpuesta,
    PrecioMinimo = @PrecioMinimo,
    PrecioMaximo = @PrecioMaximo,
    Precio = @Precio,
    Total = @Total,
    CalculoId = @CalculoId,
    UserUpdate = @UserUpdate,
    UpdatedAt = GETDATE(),
    SearchText = @SearchText
WHERE Id = @Id;
END;